//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigma.Core.Monitors.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sigma.Core.Monitors.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by ThinkingTransisitor.
        /// </summary>
        public static string AboutBoxCompany {
            get {
                return ResourceManager.GetString("AboutBoxCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made with.
        /// </summary>
        public static string AboutBoxCreated {
            get {
                return ResourceManager.GetString("AboutBoxCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigma.
        /// </summary>
        public static string AboutBoxHeader {
            get {
                return ResourceManager.GetString("AboutBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWESOME.
        /// </summary>
        public static string AboutBoxOk {
            get {
                return ResourceManager.GetString("AboutBoxOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rocket powered machine learning.
        ///Create, compare, adapt, improve - neural networks at the speed of thought.
        ///
        ///Free to use for anyone (MIT license)..
        /// </summary>
        public static string AboutBoxText {
            get {
                return ResourceManager.GetString("AboutBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string ButtonDebug {
            get {
                return ResourceManager.GetString("ButtonDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        public static string ButtonEnvironment {
            get {
                return ResourceManager.GetString("ButtonEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string ButtonHelp {
            get {
                return ResourceManager.GetString("ButtonHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ButtonSettings {
            get {
                return ResourceManager.GetString("ButtonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string CloseApp {
            get {
                return ResourceManager.GetString("CloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current activation.
        /// </summary>
        public static string CurrentActivationFunction {
            get {
                return ResourceManager.GetString("CurrentActivationFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current epoch.
        /// </summary>
        public static string CurrentEpoch {
            get {
                return ResourceManager.GetString("CurrentEpoch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current iteration.
        /// </summary>
        public static string CurrentIteration {
            get {
                return ResourceManager.GetString("CurrentIteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current operator.
        /// </summary>
        public static string CurrentOperator {
            get {
                return ResourceManager.GetString("CurrentOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current optimiser.
        /// </summary>
        public static string CurrentOptimiser {
            get {
                return ResourceManager.GetString("CurrentOptimiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Sigma.
        /// </summary>
        public static string MenuButtonAbout {
            get {
                return ResourceManager.GetString("MenuButtonAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string MenuButtonLanguage {
            get {
                return ResourceManager.GetString("MenuButtonLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string MenuButtonLoad {
            get {
                return ResourceManager.GetString("MenuButtonLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MenuButtonSave {
            get {
                return ResourceManager.GetString("MenuButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string MenuButtonStyle {
            get {
                return ResourceManager.GetString("MenuButtonStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle alternate theme.
        /// </summary>
        public static string MenuButtonToggleAlternate {
            get {
                return ResourceManager.GetString("MenuButtonToggleAlternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle dark theme.
        /// </summary>
        public static string MenuButtonToggleDark {
            get {
                return ResourceManager.GetString("MenuButtonToggleDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenApp {
            get {
                return ResourceManager.GetString("OpenApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running time.
        /// </summary>
        public static string RunningTime {
            get {
                return ResourceManager.GetString("RunningTime", resourceCulture);
            }
        }
    }
}
